# Site settings
title: Power the Polls
email: info@powerthepolls.org
description: > # this means to ignore newlines until "baseurl:"
  Help recruit the next generation of poll workers to ensure all eligible
  voters have the option to vote in person if necessary.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: powerthepolls
github_username: pizza-to-the-polls

# Build settings
markdown: kramdown
